import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import '@rainbow-me/rainbowkit/styles.css';
import './globals.css';
import LayoutHeader from '@/components/layout/layout-header';
import LayoutFooter from '@/components/layout/layout-footer';
import AppProviders from '@/components/providers/app-providers';

const manrope = Manrope({
	variable: '--font-manrope',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${manrope.variable} h-full antialiased`}
			suppressHydrationWarning
		>
			<head>
				<script
					dangerouslySetInnerHTML={{
						__html: `(function(){try{var t=localStorage.getItem('theme');var d=window.matchMedia('(prefers-color-scheme: dark)').matches;if(t==='dark'||(t===null&&d)){document.documentElement.classList.add('dark')}}catch(e){}})()`,
					}}
				/>
			</head>
			<body className="min-h-full flex flex-col">
				<AppProviders>
					<LayoutHeader />
					<div className="flex flex-col grow centered-container">
						{children}
					</div>
					<LayoutFooter />
				</AppProviders>
			</body>
		</html>
	);
}
